services:
  backend:
    image: maponomypoultry-server
    environment:
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
      APP_VERSION: ${APP_VERSION}
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
